### PR TITLE
Modify the server default TLS versions

### LINKED ISSUE #175: Disable Insecure TLS
In order to allow the default Apache configuration for the server to be used at Fermilab in accordance with our security policies, I propose that TLS1.0/1.1 be disabled in the default configuration, with an option added to enable support for them if needed.

### PR DESCRIPTION
**Pull request by bjwhite-fnal**
Closes #175

### CODE REVIEW

**Review by rcarpa — COMMENTED** [review]
I would rather use something like

```
{% if RUCIO_SSL_PROTOCOL is defined %}
 SSLProtocol              {{ RUCIO_SSL_PROTOCOL }} 
{% else %}
 SSLProtocol             all -SSLv2 -SSLv3
{% endif %}
```
to make it a bit more future proof and allow changes to this parameter without rebuilding the containers

**Comment by rcarpa** [comment]
Sorry, I meant 
```
{% if RUCIO_SSL_PROTOCOL is defined %}
 SSLProtocol              {{ RUCIO_SSL_PROTOCOL }} 
{% else %}
 SSLProtocol             +TLSv1.2
{% endif %}
```

**Comment by bari12** [comment]
I think it would be better if we wait for 1.28 for this.

**Comment by bjwhite-fnal** [comment]
I can live without it for a while. I'm still on 1.26 for all my deployments currently anyway.

**Comment by bari12** [comment]
👍 I am not sure if this is an issue for anyone, it might not be. But I would rather just change it with a feature release where people are prepared for such a change.

**Pull request merged**
